version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: webhook-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: webhook_dispatcher
    ports:
      - "5432:5432" # PostgreSQL port
    volumes:
      - pgdata:/var/lib/postgresql/data #guardar info
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: webhook-queue
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" # RabbitMQ management port

    restart: unless-stopped
  volumes:
    pgdata: 